# Generated by Django 4.2.1 on 2023-05-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Упакован', 'Упакован'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен'), ('Отмена', 'Отмена'), ('В ожидании', 'В ожидании')], default='В ожидании', max_length=50),
        ),
    ]
