# Generated by Django 4.2.1 on 2023-06-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='адрес',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='город',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='имя',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='номер_телефона',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='zipcode',
            new_name='почтовый_индекс',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='country',
            new_name='страна',
        ),
    ]
